class ICONS {
  //////////////===============PNG===============//////////////
  static const String IC_BACK_PNG = 'assets/icons/back_icon.png';
  static const String IC_FACE_PNG = 'assets/icons/figerprint_faceid.png';
  static const String IC_MENU_HOME_PNG = 'assets/icons/trangchu.png';
  static const String IC_USER_PNG = 'assets/icons/account.png';
  static const String IC_CHANGE_PASS_WORK_PNG =
      'assets/icons/changepassWork.png';
  static const String IC_POLICY_PNG = 'assets/icons/policy.png';
  static const String IC_ABOUT_US_PNG = 'assets/icons/aboutUs.png';
  static const String IC_LOGO_PNG = 'assets/icons/logo.png';
  static const String IC_DATE_PNG = 'assets/icons/date.png';
  static const String IC_DELETE_PNG = 'assets/icons/icon_delete.png';
  static const String IC_ATTACK_SVG = 'assets/icons/attack.svg';
  static const String IC_HOP_DONG_PNG = 'assets/icons/hopdong.png';
  static const String IC_CONTENT_PNG = 'assets/icons/addContent.png';
  static const String IC_EDIT_2_PNG = 'assets/icons/edit.png';
  static const String IC_REMOVE_PNG = 'assets/icons/remove.png';
  static const String IC_RED_PNG = 'assets/icons/red.png';
  static const String IC_CART_PNG = 'assets/icons/iconCart.png';
  static const String IC_MINUS_PNG = 'assets/icons/minus.png';
  static const String IC_PLUS_PNG = 'assets/icons/plus.png';
  static const String IC_MENU_PNG = 'assets/icons/Menu.png';
  static const String IC_SEND_PNG = 'assets/icons/send.png';
  static const String IC_EDIT_PNG = 'assets/icons/icon_edit.png';
  static const String IC_MAY_ANH_PNG = 'assets/icons/mayanh.png';
  static const String IC_WORK2_PNG = 'assets/icons/Work.png';
  static const String IC_FAVICON_PNG = 'assets/icons/favicon.png';
  static const String IC_LICENSE_PLATE_PNG = 'assets/icons/license-plate.png';
  static const String IC_ELECTRIC_SIGN_PNG = 'assets/icons/sign.png';
  static const String IC_STAR_PNG = 'assets/icons/star.png';
  static const String IC_STAR_BOLD_PNG = 'assets/icons/star_bold.png';
  static const String IC_PROFILE_ERROR_PNG = 'assets/icons/profile_error.png';
  static const String IC_REMOVE_TXT_PNG = 'assets/icons/remove_txt.png';
  static const String IC_HIDE_PNG = 'assets/icons/hide.png';
  static const String IC_SHOW_PNG = 'assets/icons/show.png';
  static const String IC_PHONE_PNG = 'assets/icons/phone.png';
  static const String IC_COPY_PNG = 'assets/icons/copy.png';
  static const String IC_PASTE_PNG = 'assets/icons/paste.png';
  static const String IC_RELOAD_PNG = 'assets/icons/reload.png';

  static const String IC_CUSTOMER_3X_PNG = 'assets/icons/Custumer_3x.png';
  static const String IC_CLUE_3X_PNG = 'assets/icons/Clue_3x.png';
  static const String IC_CHANCE_3X_PNG = 'assets/icons/Chance_3x.png';
  static const String IC_CONTRACT_3X_PNG = 'assets/icons/Contract_3x.png';
  static const String IC_WORK_3X_PNG = 'assets/icons/Work_3x.png';
  static const String IC_SUPPORT_3X_PNG = 'assets/icons/Support_3x.png';
  static const String IC_REPORT_PNG = 'assets/icons/insights.png';
  static const String IC_DELETE_TEXT_PNG = 'assets/icons/delete_text.png';

  static const String IC_FLAG_VI = 'assets/icons/vietnam.png';
  static const String IC_FLAG_KO = 'assets/icons/south-korea.png';
  static const String IC_FLAG_EN = 'assets/icons/united-kingdom.png';

  //////////////===============SVG===============//////////////
  static const String IC_MAIL_CUSTOMER_SVG = 'assets/icons/mail_customer.svg';
  static const String IC_ADD_CLUE_SVG = 'assets/icons/addclue.svg';
  static const String IC_ICON3_SVG = 'assets/icons/icon3.svg';
  static const String IC_ADD_CHANCE_SVG = 'assets/icons/addchance.svg';
  static const String IC_ADD_CONTRACT_SVG = 'assets/icons/addcontract.svg';
  static const String IC_ADD_WORD_SVG = 'assets/icons/addwork.svg';
  static const String IC_ADD_SUPPORT_SVG = 'assets/icons/addsupport.svg';
  static const String IC_ADD_DISCUSS_SVG = 'assets/icons/adddiscuss.svg';
  static const String IC_EDIT_SVG = 'assets/icons/edit.svg';
  static const String IC_DELETE_SVG = 'assets/icons/delete.svg';
  static const String IC_MENU_SVG = 'assets/icons/menu.svg';
  static const String IC_AVATAR_SVG = 'assets/icons/avatar_customer.svg';
  static const String IC_SEARCH_SVG = 'assets/icons/search_customer.svg';
  static const String IC_SEARCH2_SVG = 'assets/icons/Search.svg';
  static const String IC_ICON4_SVG = 'assets/icons/icon4.svg';
  static const String IC_QUESTION_SVG = 'assets/icons/question_answer.svg';
  static const String IC_FILL_SVG = 'assets/icons/fill_customer.svg';
  static const String IC_FILTER_SVG = 'assets/icons/Filter.svg';
  static const String IC_MAIL_SVG = 'assets/icons/mail.svg';
  static const String IC_CALL_SVG = 'assets/icons/Call.svg';
  static const String IC_PHONE_CUSTOMER_SVG = 'assets/icons/phone_customer.svg';
  static const String IC_MESS = 'assets/icons/Mess.svg';
  static const String IC_NOTIFICATION_SVG = 'assets/icons/notification.svg';
  static const String IC_NOTIFICATION2_SVG = 'assets/icons/notification2.svg';
  static const String IC_INPUT_SVG = 'assets/icons/iconInputImg.svg';
  static const String IC_USER2_SVG = 'assets/icons/User.svg';
  static const String IC_DANG_XU_LY_SVG = 'assets/icons/dangxuly.svg';
  static const String IC_HINT_SVG = 'assets/icons/pass.svg';
  static const String IC_BUILD_SVG = 'assets/icons/building.svg';
  static const String IC_CART_SVG = 'assets/icons/cart.svg';
  static const String IC_LOCATION_PNG = 'assets/icons/location_customer.svg';
  static const String IC_ICON1_SVG = 'assets/icons/icon1.svg';
  static const String IC_LOCATION_SVG = 'assets/icons/location_pin.svg';
}
