const empty = {'name': ''};

const List<Map<String, dynamic>> DATA_TINH_THANH_ALL = [
  {
    "id": "",
    "name": "Tỉnh thành",
  },
  {
    "id": "242",
    "type": "40",
    "parentId": "0",
    "name": "Hà Nội",
    "note": "",
    "option": "",
    "order": "51",
    "code": "HN",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "244",
    "type": "40",
    "parentId": "0",
    "name": "Hồ Chí Minh",
    "note": "",
    "option": "",
    "order": "53",
    "code": "HCM",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "10002",
    "type": "40",
    "parentId": "0",
    "name": "Lâm Đồng",
    "note": "",
    "option": "",
    "order": "67",
    "code": "LD",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "10004",
    "type": "40",
    "parentId": "0",
    "name": "Bến Tre",
    "note": "",
    "option": "",
    "order": "67",
    "code": "BTR",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "10003",
    "type": "40",
    "parentId": "0",
    "name": "Đồng Tháp",
    "note": "",
    "option": "",
    "order": "64",
    "code": "DT",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "192",
    "type": "40",
    "parentId": "0",
    "name": "Bình Định",
    "note": "",
    "option": "",
    "order": "2",
    "code": "BD",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "193",
    "type": "40",
    "parentId": "0",
    "name": "An Giang",
    "note": "",
    "option": "",
    "order": "1",
    "code": "AG",
    "color": "#FB4C2F",
    "uid": null,
    "ci": null
  },
  {
    "id": "194",
    "type": "40",
    "parentId": "0",
    "name": "Bà Rịa - Vũng Tàu",
    "note": "",
    "option": "",
    "order": "3",
    "code": "BR",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "195",
    "type": "40",
    "parentId": "0",
    "name": "Bắc Kạn",
    "note": "",
    "option": "",
    "order": "4",
    "code": "BC",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "196",
    "type": "40",
    "parentId": "0",
    "name": "Bắc Giang",
    "note": "",
    "option": "",
    "order": "5",
    "code": "BG",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "197",
    "type": "40",
    "parentId": "0",
    "name": "Bạc Liêu",
    "note": "",
    "option": "",
    "order": "6",
    "code": "BL",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "198",
    "type": "40",
    "parentId": "0",
    "name": "Bắc Ninh",
    "note": "",
    "option": "",
    "order": "7",
    "code": "BN",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "199",
    "type": "40",
    "parentId": "0",
    "name": "Bình Thuận",
    "note": "",
    "option": "",
    "order": "11",
    "code": "BT",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "200",
    "type": "40",
    "parentId": "0",
    "name": "Bình Dương",
    "note": "",
    "option": "",
    "order": "9",
    "code": "BDU",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "201",
    "type": "40",
    "parentId": "0",
    "name": "Bình Phước",
    "note": "",
    "option": "",
    "order": "10",
    "code": "BP",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "203",
    "type": "40",
    "parentId": "0",
    "name": "Cà Mau",
    "note": "",
    "option": "",
    "order": "12",
    "code": "CM",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "204",
    "type": "40",
    "parentId": "0",
    "name": "Cao Bằng",
    "note": "",
    "option": "",
    "order": "13",
    "code": "CB",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "205",
    "type": "40",
    "parentId": "0",
    "name": "Gia Lai",
    "note": "",
    "option": "",
    "order": "14",
    "code": "GL",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "206",
    "type": "40",
    "parentId": "0",
    "name": "Hậu Giang",
    "note": "",
    "option": "",
    "order": "20",
    "code": "HGI",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "207",
    "type": "40",
    "parentId": "0",
    "name": "Hà Nam",
    "note": "",
    "option": "",
    "order": "16",
    "code": "HNA",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "209",
    "type": "40",
    "parentId": "0",
    "name": "Hà Tĩnh",
    "note": "",
    "option": "",
    "order": "18",
    "code": "HTI",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "210",
    "type": "40",
    "parentId": "0",
    "name": "Hải Dương",
    "note": "",
    "option": "",
    "order": "19",
    "code": "HD",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "211",
    "type": "40",
    "parentId": "0",
    "name": "Hà Giang",
    "note": "",
    "option": "",
    "order": "20",
    "code": "HG",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "212",
    "type": "40",
    "parentId": "0",
    "name": "Hưng yên",
    "note": "",
    "option": "",
    "order": "21",
    "code": "HY",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "213",
    "type": "40",
    "parentId": "0",
    "name": "Khánh Hòa",
    "note": "",
    "option": "",
    "order": "22",
    "code": "KH",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "214",
    "type": "40",
    "parentId": "0",
    "name": "Kiên Giang",
    "note": "",
    "option": "",
    "order": "23",
    "code": "KG",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "215",
    "type": "40",
    "parentId": "0",
    "name": "Kon Tum",
    "note": "",
    "option": "",
    "order": "24",
    "code": "KT",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "216",
    "type": "40",
    "parentId": "0",
    "name": "Lai Châu",
    "note": "",
    "option": "",
    "order": "25",
    "code": "LC",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "218",
    "type": "40",
    "parentId": "0",
    "name": "Lạng Sơn",
    "note": "",
    "option": "",
    "order": "27",
    "code": "LS",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "219",
    "type": "40",
    "parentId": "0",
    "name": "Lào Cai",
    "note": "",
    "option": "",
    "order": "28",
    "code": "LCA",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "220",
    "type": "40",
    "parentId": "0",
    "name": "Long An",
    "note": "",
    "option": "",
    "order": "29",
    "code": "LA",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "221",
    "type": "40",
    "parentId": "0",
    "name": "Nam Định",
    "note": "",
    "option": "",
    "order": "30",
    "code": "ND",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "222",
    "type": "40",
    "parentId": "0",
    "name": "Nghệ An",
    "note": "",
    "option": "",
    "order": "31",
    "code": "NA",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "223",
    "type": "40",
    "parentId": "0",
    "name": "Ninh Bình",
    "note": "",
    "option": "",
    "order": "32",
    "code": "NB",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "224",
    "type": "40",
    "parentId": "0",
    "name": "Ninh Thuận",
    "note": "",
    "option": "",
    "order": "33",
    "code": "NTH",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "225",
    "type": "40",
    "parentId": "0",
    "name": "Phú Thọ",
    "note": "",
    "option": "",
    "order": "34",
    "code": "PT",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "226",
    "type": "40",
    "parentId": "0",
    "name": "Phú Yên",
    "note": "",
    "option": "",
    "order": "35",
    "code": "PY",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "227",
    "type": "40",
    "parentId": "0",
    "name": "Quảng Bình",
    "note": "",
    "option": "",
    "order": "36",
    "code": "QB",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "228",
    "type": "40",
    "parentId": "0",
    "name": "Quảng Nam",
    "note": "",
    "option": "",
    "order": "37",
    "code": "QNA",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "229",
    "type": "40",
    "parentId": "0",
    "name": "Quảng Ngãi",
    "note": "",
    "option": "",
    "order": "38",
    "code": "QNG",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "230",
    "type": "40",
    "parentId": "0",
    "name": "Quảng Ninh",
    "note": "",
    "option": "",
    "order": "39",
    "code": "QN",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "231",
    "type": "40",
    "parentId": "0",
    "name": "Quảng Trị",
    "note": "",
    "option": "",
    "order": "40",
    "code": "QTR",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "232",
    "type": "40",
    "parentId": "0",
    "name": "Sóc Trăng",
    "note": "",
    "option": "",
    "order": "41",
    "code": "ST",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "233",
    "type": "40",
    "parentId": "0",
    "name": "Sơn La",
    "note": "",
    "option": "",
    "order": "42",
    "code": "SL",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "234",
    "type": "40",
    "parentId": "0",
    "name": "Tây Ninh",
    "note": "",
    "option": "",
    "order": "43",
    "code": "TN",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "235",
    "type": "40",
    "parentId": "0",
    "name": "Thái Bình",
    "note": "",
    "option": "",
    "order": "44",
    "code": "TB",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "236",
    "type": "40",
    "parentId": "0",
    "name": "Thái Nguyên",
    "note": "",
    "option": "",
    "order": "45",
    "code": "TNG",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "237",
    "type": "40",
    "parentId": "0",
    "name": "Thanh Hóa",
    "note": "",
    "option": "",
    "order": "46",
    "code": "TH",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "238",
    "type": "40",
    "parentId": "0",
    "name": "Thừa Thiên Huế",
    "note": "",
    "option": "",
    "order": "47",
    "code": "TTH",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "239",
    "type": "40",
    "parentId": "0",
    "name": "Tiền Giang",
    "note": "",
    "option": "",
    "order": "48",
    "code": "TG",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "240",
    "type": "40",
    "parentId": "0",
    "name": "Hòa Bình",
    "note": "",
    "option": "",
    "order": "49",
    "code": "HB",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "241",
    "type": "40",
    "parentId": "0",
    "name": "Cần Thơ",
    "note": "",
    "option": "",
    "order": "50",
    "code": "CT",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "243",
    "type": "40",
    "parentId": "0",
    "name": "Hải Phòng",
    "note": "",
    "option": "",
    "order": "52",
    "code": "HP",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "245",
    "type": "40",
    "parentId": "0",
    "name": "Trà Vinh",
    "note": "",
    "option": "",
    "order": "54",
    "code": "TV",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "246",
    "type": "40",
    "parentId": "0",
    "name": "Tuyên Quang",
    "note": "",
    "option": "",
    "order": "55",
    "code": "TQ",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "247",
    "type": "40",
    "parentId": "0",
    "name": "Vĩnh Long",
    "note": "",
    "option": "",
    "order": "56",
    "code": "VL",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "248",
    "type": "40",
    "parentId": "0",
    "name": "Vĩnh Phúc",
    "note": "",
    "option": "",
    "order": "57",
    "code": "VP",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "249",
    "type": "40",
    "parentId": "0",
    "name": "Yên Bái",
    "note": "",
    "option": "",
    "order": "58",
    "code": "YB",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "250",
    "type": "40",
    "parentId": "0",
    "name": "Đà Nẵng",
    "note": "",
    "option": "",
    "order": "59",
    "code": "DNA",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "251",
    "type": "40",
    "parentId": "0",
    "name": "Đắk Lắk",
    "note": "",
    "option": "",
    "order": "60",
    "code": "DL",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "252",
    "type": "40",
    "parentId": "0",
    "name": "Đắk Nông",
    "note": "",
    "option": "",
    "order": "61",
    "code": "DNO",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "253",
    "type": "40",
    "parentId": "0",
    "name": "Điện Biên",
    "note": "",
    "option": "",
    "order": "62",
    "code": "DBI",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "254",
    "type": "40",
    "parentId": "0",
    "name": "Đồng Nai",
    "note": "",
    "option": "",
    "order": "63",
    "code": "DN",
    "color": null,
    "uid": null,
    "ci": null
  }
];

const List<Map<String, dynamic>> DATA_TINH_THANH = [
  {
    "id": "242",
    "type": "40",
    "parentId": "0",
    "name": "Hà Nội",
    "note": "",
    "option": "",
    "order": "51",
    "code": "HN",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "244",
    "type": "40",
    "parentId": "0",
    "name": "Hồ Chí Minh",
    "note": "",
    "option": "",
    "order": "53",
    "code": "HCM",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "10002",
    "type": "40",
    "parentId": "0",
    "name": "Lâm Đồng",
    "note": "",
    "option": "",
    "order": "67",
    "code": "LD",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "10004",
    "type": "40",
    "parentId": "0",
    "name": "Bến Tre",
    "note": "",
    "option": "",
    "order": "67",
    "code": "BTR",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "10003",
    "type": "40",
    "parentId": "0",
    "name": "Đồng Tháp",
    "note": "",
    "option": "",
    "order": "64",
    "code": "DT",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "192",
    "type": "40",
    "parentId": "0",
    "name": "Bình Định",
    "note": "",
    "option": "",
    "order": "2",
    "code": "BD",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "193",
    "type": "40",
    "parentId": "0",
    "name": "An Giang",
    "note": "",
    "option": "",
    "order": "1",
    "code": "AG",
    "color": "#FB4C2F",
    "uid": null,
    "ci": null
  },
  {
    "id": "194",
    "type": "40",
    "parentId": "0",
    "name": "Bà Rịa - Vũng Tàu",
    "note": "",
    "option": "",
    "order": "3",
    "code": "BR",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "195",
    "type": "40",
    "parentId": "0",
    "name": "Bắc Kạn",
    "note": "",
    "option": "",
    "order": "4",
    "code": "BC",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "196",
    "type": "40",
    "parentId": "0",
    "name": "Bắc Giang",
    "note": "",
    "option": "",
    "order": "5",
    "code": "BG",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "197",
    "type": "40",
    "parentId": "0",
    "name": "Bạc Liêu",
    "note": "",
    "option": "",
    "order": "6",
    "code": "BL",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "198",
    "type": "40",
    "parentId": "0",
    "name": "Bắc Ninh",
    "note": "",
    "option": "",
    "order": "7",
    "code": "BN",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "199",
    "type": "40",
    "parentId": "0",
    "name": "Bình Thuận",
    "note": "",
    "option": "",
    "order": "11",
    "code": "BT",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "200",
    "type": "40",
    "parentId": "0",
    "name": "Bình Dương",
    "note": "",
    "option": "",
    "order": "9",
    "code": "BDU",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "201",
    "type": "40",
    "parentId": "0",
    "name": "Bình Phước",
    "note": "",
    "option": "",
    "order": "10",
    "code": "BP",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "203",
    "type": "40",
    "parentId": "0",
    "name": "Cà Mau",
    "note": "",
    "option": "",
    "order": "12",
    "code": "CM",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "204",
    "type": "40",
    "parentId": "0",
    "name": "Cao Bằng",
    "note": "",
    "option": "",
    "order": "13",
    "code": "CB",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "205",
    "type": "40",
    "parentId": "0",
    "name": "Gia Lai",
    "note": "",
    "option": "",
    "order": "14",
    "code": "GL",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "206",
    "type": "40",
    "parentId": "0",
    "name": "Hậu Giang",
    "note": "",
    "option": "",
    "order": "20",
    "code": "HGI",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "207",
    "type": "40",
    "parentId": "0",
    "name": "Hà Nam",
    "note": "",
    "option": "",
    "order": "16",
    "code": "HNA",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "209",
    "type": "40",
    "parentId": "0",
    "name": "Hà Tĩnh",
    "note": "",
    "option": "",
    "order": "18",
    "code": "HTI",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "210",
    "type": "40",
    "parentId": "0",
    "name": "Hải Dương",
    "note": "",
    "option": "",
    "order": "19",
    "code": "HD",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "211",
    "type": "40",
    "parentId": "0",
    "name": "Hà Giang",
    "note": "",
    "option": "",
    "order": "20",
    "code": "HG",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "212",
    "type": "40",
    "parentId": "0",
    "name": "Hưng yên",
    "note": "",
    "option": "",
    "order": "21",
    "code": "HY",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "213",
    "type": "40",
    "parentId": "0",
    "name": "Khánh Hòa",
    "note": "",
    "option": "",
    "order": "22",
    "code": "KH",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "214",
    "type": "40",
    "parentId": "0",
    "name": "Kiên Giang",
    "note": "",
    "option": "",
    "order": "23",
    "code": "KG",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "215",
    "type": "40",
    "parentId": "0",
    "name": "Kon Tum",
    "note": "",
    "option": "",
    "order": "24",
    "code": "KT",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "216",
    "type": "40",
    "parentId": "0",
    "name": "Lai Châu",
    "note": "",
    "option": "",
    "order": "25",
    "code": "LC",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "218",
    "type": "40",
    "parentId": "0",
    "name": "Lạng Sơn",
    "note": "",
    "option": "",
    "order": "27",
    "code": "LS",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "219",
    "type": "40",
    "parentId": "0",
    "name": "Lào Cai",
    "note": "",
    "option": "",
    "order": "28",
    "code": "LCA",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "220",
    "type": "40",
    "parentId": "0",
    "name": "Long An",
    "note": "",
    "option": "",
    "order": "29",
    "code": "LA",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "221",
    "type": "40",
    "parentId": "0",
    "name": "Nam Định",
    "note": "",
    "option": "",
    "order": "30",
    "code": "ND",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "222",
    "type": "40",
    "parentId": "0",
    "name": "Nghệ An",
    "note": "",
    "option": "",
    "order": "31",
    "code": "NA",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "223",
    "type": "40",
    "parentId": "0",
    "name": "Ninh Bình",
    "note": "",
    "option": "",
    "order": "32",
    "code": "NB",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "224",
    "type": "40",
    "parentId": "0",
    "name": "Ninh Thuận",
    "note": "",
    "option": "",
    "order": "33",
    "code": "NTH",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "225",
    "type": "40",
    "parentId": "0",
    "name": "Phú Thọ",
    "note": "",
    "option": "",
    "order": "34",
    "code": "PT",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "226",
    "type": "40",
    "parentId": "0",
    "name": "Phú Yên",
    "note": "",
    "option": "",
    "order": "35",
    "code": "PY",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "227",
    "type": "40",
    "parentId": "0",
    "name": "Quảng Bình",
    "note": "",
    "option": "",
    "order": "36",
    "code": "QB",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "228",
    "type": "40",
    "parentId": "0",
    "name": "Quảng Nam",
    "note": "",
    "option": "",
    "order": "37",
    "code": "QNA",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "229",
    "type": "40",
    "parentId": "0",
    "name": "Quảng Ngãi",
    "note": "",
    "option": "",
    "order": "38",
    "code": "QNG",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "230",
    "type": "40",
    "parentId": "0",
    "name": "Quảng Ninh",
    "note": "",
    "option": "",
    "order": "39",
    "code": "QN",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "231",
    "type": "40",
    "parentId": "0",
    "name": "Quảng Trị",
    "note": "",
    "option": "",
    "order": "40",
    "code": "QTR",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "232",
    "type": "40",
    "parentId": "0",
    "name": "Sóc Trăng",
    "note": "",
    "option": "",
    "order": "41",
    "code": "ST",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "233",
    "type": "40",
    "parentId": "0",
    "name": "Sơn La",
    "note": "",
    "option": "",
    "order": "42",
    "code": "SL",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "234",
    "type": "40",
    "parentId": "0",
    "name": "Tây Ninh",
    "note": "",
    "option": "",
    "order": "43",
    "code": "TN",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "235",
    "type": "40",
    "parentId": "0",
    "name": "Thái Bình",
    "note": "",
    "option": "",
    "order": "44",
    "code": "TB",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "236",
    "type": "40",
    "parentId": "0",
    "name": "Thái Nguyên",
    "note": "",
    "option": "",
    "order": "45",
    "code": "TNG",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "237",
    "type": "40",
    "parentId": "0",
    "name": "Thanh Hóa",
    "note": "",
    "option": "",
    "order": "46",
    "code": "TH",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "238",
    "type": "40",
    "parentId": "0",
    "name": "Thừa Thiên Huế",
    "note": "",
    "option": "",
    "order": "47",
    "code": "TTH",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "239",
    "type": "40",
    "parentId": "0",
    "name": "Tiền Giang",
    "note": "",
    "option": "",
    "order": "48",
    "code": "TG",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "240",
    "type": "40",
    "parentId": "0",
    "name": "Hòa Bình",
    "note": "",
    "option": "",
    "order": "49",
    "code": "HB",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "241",
    "type": "40",
    "parentId": "0",
    "name": "Cần Thơ",
    "note": "",
    "option": "",
    "order": "50",
    "code": "CT",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "243",
    "type": "40",
    "parentId": "0",
    "name": "Hải Phòng",
    "note": "",
    "option": "",
    "order": "52",
    "code": "HP",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "245",
    "type": "40",
    "parentId": "0",
    "name": "Trà Vinh",
    "note": "",
    "option": "",
    "order": "54",
    "code": "TV",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "246",
    "type": "40",
    "parentId": "0",
    "name": "Tuyên Quang",
    "note": "",
    "option": "",
    "order": "55",
    "code": "TQ",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "247",
    "type": "40",
    "parentId": "0",
    "name": "Vĩnh Long",
    "note": "",
    "option": "",
    "order": "56",
    "code": "VL",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "248",
    "type": "40",
    "parentId": "0",
    "name": "Vĩnh Phúc",
    "note": "",
    "option": "",
    "order": "57",
    "code": "VP",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "249",
    "type": "40",
    "parentId": "0",
    "name": "Yên Bái",
    "note": "",
    "option": "",
    "order": "58",
    "code": "YB",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "250",
    "type": "40",
    "parentId": "0",
    "name": "Đà Nẵng",
    "note": "",
    "option": "",
    "order": "59",
    "code": "DNA",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "251",
    "type": "40",
    "parentId": "0",
    "name": "Đắk Lắk",
    "note": "",
    "option": "",
    "order": "60",
    "code": "DL",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "252",
    "type": "40",
    "parentId": "0",
    "name": "Đắk Nông",
    "note": "",
    "option": "",
    "order": "61",
    "code": "DNO",
    "color": null,
    "uid": null,
    "ci": null
  },
  {
    "id": "253",
    "type": "40",
    "parentId": "0",
    "name": "Điện Biên",
    "note": "",
    "option": "",
    "order": "62",
    "code": "DBI",
    "color": "",
    "uid": null,
    "ci": null
  },
  {
    "id": "254",
    "type": "40",
    "parentId": "0",
    "name": "Đồng Nai",
    "note": "",
    "option": "",
    "order": "63",
    "code": "DN",
    "color": null,
    "uid": null,
    "ci": null
  }
];

String getNameTinhThanh(String id) {
  for (final element in DATA_TINH_THANH) {
    if (element['id'] == id) {
      return element['name'];
    }
  }
  return '';
}

String checkTitle(data, title) {
  return data == '' ? title : data ?? title;
}
